name: Deploy Check
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        include:
          # Mainnets
          - name: Optimism
            chain: optimism
          - name: Telos
            chain: telos
          - name: BNB Smart Chain
            chain: bsc
          - name: Gnosis Chain
            chain: gnosis
          - name: Polygon
            chain: polygon
          - name: Polygon zkEVM
            chain: polygon-zkevm
          - name: Moonbeam
            chain: moonbeam
          - name: Soneium
            chain: soneium
          - name: LAOS
            chain: laos
          - name: The Root Network
            chain: rootnet
          - name: B3
            chain: b3
          - name: Base (Coinbase)
            chain: base
          - name: Immutable zkEVM
            chain: immutable-zkevm
          - name: Oasys Homeverse
            chain: homeverse
          - name: APE Chain
            chain: apechain
          - name: Arbitrum One
            chain: arbitrum
          - name: Arbitrum Nova
            chain: arbitrum-nova
          - name: Etherlink
            chain: etherlink
          - name: Avalanche
            chain: avalanche
          - name: Blast
            chain: blast
          - name: Xai
            chain: xai
          - name: SKALE Nebula Gaming Hub
            chain: skale-nebula
          # Testnets
          - name: Telos Testnet
            chain: telos-testnet
          - name: BNB Smart Chain Testnet
            chain: bsc-testnet
          - name: Moonbase Alpha
            chain: moonbase-alpha
          - name: Soneium Minato (Testnet)
            chain: soneium-minato
          - name: B3 Sepolia
            chain: b3-sepolia
          - name: The Root Network Porcini Testnet
            chain: rootnet-porcini
          - name: Monad Testnet
            chain: monad-testnet
          - name: Immutable zkEVM Testnet
            chain: immutable-zkevm-testnet
          - name: APE Chain Testnet
            chain: apechain-testnet
          - name: Oasys Homeverse Testnet
            chain: homeverse-testnet
          - name: Avalanche Testnet
            chain: avalanche-testnet
          - name: Somnia Testnet
            chain: somnia-testnet
          - name: Frequency Testnet
            chain: frequency-testnet
          - name: LAOS Sigma Testnet
            chain: laos-sigma-testnet
          - name: Polygon Amoy
            chain: amoy
          - name: Base Sepolia
            chain: base-sepolia
          - name: Etherlink Testnet
            chain: etherlink-testnet
          - name: Arbitrum Sepolia
            chain: arbitrum-sepolia
          - name: Sepolia
            chain: sepolia
          - name: Optimism Sepolia
            chain: optimism-sepolia
          - name: TOY (Testnet)
            chain: toy-testnet
          - name: SKALE Nebula Gaming Hub Testnet
            chain: skale-nebula-testnet
          - name: Blast Sepolia
            chain: blast-sepolia
          - name: XAI Sepolia
            chain: xai-sepolia

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Set env vars
        run: |
          echo "DEFAULT_TIMEOUT_MS=1000000" >> $GITHUB_ENV
          echo "DEPLOYER_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" >> $GITHUB_ENV

      - name: Write config
        run: |
          echo '[{"networkName": "${{ matrix.chain }}", "rpcUrl": "https://nodes.sequence.app/${{ matrix.chain }}"}]' > config.json

      - name: Deploy to ${{ matrix.name }}
        run: |
          echo "Deploying to ${{ matrix.name }}..."
          yarn deploy ${{ matrix.chain }}

      - name: Report success
        run: |
          output_file="output_${{ matrix.chain }}.json"
          if [ -f "$output_file" ]; then
            echo "Success: true"
            echo "Output file contents:"
            cat "$output_file"
            exit 0
          else
            echo "Success: false"
            echo "Output file $output_file not found"
            exit 1
          fi
